#### Adding

#### Deleting

{docs delete-item}
{docs delete-element}
{docs delete-node}

#### Getting

{docs nth-item}
{docs nth-element}
{docs item-at}
{docs item-at-1}

#### Specialized

These operations are essentially synonyms for the generic container methods. They are included to make working with queues and stacks feel more natural.

{docs enqueue}
{docs dequeue}
{docs push-item}
{docs pop-item}
