CL-Containers includes a set of classes to implement forward iterators and simple generators (where the latter is a sort of infinite instance of the former). 

To iterate, you create an iterator on a container and then move forward until the iterator is exhausted. 

#### Creating an iterator

{docs base-class-for-iteratee}
{docs class-for-contents-as}
{docs setup-initial-container}

{docs open-file-for-iterator}
{docs finish}

#### Using an iterator

{docs with-iterator}

{docs move-p}
{docs element-passes-p}
{docs move}
{docs advance}
{docs current-element}
{docs current-element-p}
{docs iterate-forward}
{docs move-forward}
{docs move-forward-to-next-element}
{docs next-element}
{docs reset}

