Once you have a container, it is very common to want to map some function over its contents or to want to collect its contents for some other purpose. The following functions support these desires.

{docs iterate-nodes}
{docs iterate-elements}
{docs iterate-elements-stably}
{docs iterate-keys}
{docs iterate-key-value}
{docs iterate-key-value-stably}

{docs collect-items}
{docs collect-nodes}
{docs collect-elements}
{docs collect-keys}
{docs collect-key-value}
{docs collect-elements-stably}
{docs collect-key-value-stably}

{docs count-elements}
{docs count-items}
{docs count-elements-if}
