### What's missing

### What's included that shouldn't be

### Delete

* drop collect-items
* drop delete-item
* drop find-item

### Add

* add count-nodes and count-nodes-if
* add collect-nodes-stably
* maybe add emptyp to iterator protocol

### Rename

* s/some-item/some-node/
* s/every-item/every-node/

* item-at
* item-at-1
* push-item
* pop-item